export const firstHouseRulershipInterpretations = {
  "1": "With the ruler of the 1st house in the 1st house, you have a strong sense of self and a natural confidence. You are likely to be very self-aware and have a clear understanding of your identity. This placement can also indicate a strong physical presence and a desire to be in the spotlight.",
  "2": "With the ruler of the 1st house in the 2nd house, your physical body, sense of self, and even life direction is closely tied to your values and possessions. You may find that your self-esteem is influenced by your material security and the things you own. This placement can also indicate a strong desire for financial stability and a talent for managing resources.",
  "3": "With the ruler of the 1st house in the 3rd house, your  physical body, sense of self, and life direction is closely tied to communication and learning. You may find that you express yourself through writing, speaking, or other forms of communication. This placement can also indicate a strong desire for intellectual stimulation and a talent for learning new things.",
  "4": "With the ruler of the 1st house in the 4th house, your  physical body, sense of self, and life direction is closely tied to your home and family. You may find that your identity is influenced by your upbringing and family dynamics. This placement can also indicate a strong desire for emotional security and a talent for creating a comfortable home environment.",
  "5": "With the ruler of the 1st house in the 5th house, your  physical body, sense of self, and life direction is closely tied to creativity and self-expression. You may find that you express yourself through art, music, or other creative pursuits. This placement can also indicate a strong desire for romance and a talent for enjoying life’s pleasures.",
  "6": "With the ruler of the 1st house in the 6th house, your  physical body, sense of self, and life direction is closely tied to work and health. You may find that you express yourself through your job or daily routines. This placement can also indicate a strong desire for order and a talent for taking care of yourself and others.",
  "7": "With the ruler of the 1st house in the 7th house, your  physical body, sense of self, and life direction is closely tied to relationships and partnerships. You may find that you express yourself through your interactions with others. This placement can also indicate a strong desire for companionship and a talent for forming close connections.",
  "8": "With the ruler of the 1st house in the 8th house, your  physical body, sense of self, and life direction is closely tied to transformation and shared resources. You may find that you express yourself through deep emotional connections and experiences. This placement can also indicate a strong desire for intimacy and a talent for navigating complex emotional landscapes.",
  "9": "With the ruler of the 1st house in the 9th house, your  physical body, sense of self, and life direction is closely tied to philosophy and higher learning. You may find that you express yourself through your beliefs and worldview. This placement can also indicate a strong desire for adventure and a talent for exploring new ideas and cultures.",
  "10": "With the ruler of the 1st house in the 10th house, your  physical body, sense of self, and life direction is closely tied to career and public image. You may find that you express yourself through your professional achievements and reputation. This placement can also indicate a strong desire for success and a talent for leadership.",
  "11": "With the ruler of the 1st house in the 11th house, your  physical body, sense of self, and life direction is closely tied to friendships and social groups. You may find that you express yourself through your connections with others. This placement can also indicate a strong desire for community and a talent for networking.",
  "12": "With the ruler of the 1st house in the 12th house, your  physical body, sense of self, and life direction is closely tied to the subconscious and spiritual realms. You may find that you express yourself through introspection and connection to something greater than yourself. This placement can also indicate a strong desire for solitude and a talent for understanding the deeper mysteries of life.",
};

export const secondHouseRulershipInterpretations = {
  "1": "With the ruler of the 2nd house in the 1st house, your values and possessions are closely tied to your sense of self and physical body. You may find that your self-esteem is influenced by your material security and the things you own. This placement can also indicate a strong desire for financial stability and a talent for managing resources.",
  "2": "With the ruler of the 2nd house in the 2nd house, your values and possessions are closely tied to your sense of self and physical body. You may find that your self-esteem is influenced by your material security and the things you own. This placement can also indicate a strong desire for financial stability and a talent for managing resources.",
  "3": "With the ruler of the 2nd house in the 3rd house, your values and possessions are closely tied to communication and learning. You may find that you express yourself through writing, speaking, or other forms of communication. This placement can also indicate a strong desire for intellectual stimulation and a talent for learning new things.",
  "4": "With the ruler of the 2nd house in the 4th house, your values and possessions are closely tied to your home and family. You may find that your identity is influenced by your upbringing and family dynamics. This placement can also indicate a strong desire for emotional security and a talent for creating a comfortable home environment.",
  "5": "With the ruler of the 2nd house in the 5th house, your values and possessions are closely tied to creativity and self-expression. You may find that you express yourself through art, music, or other creative pursuits. This placement can also indicate a strong desire for romance and a talent for enjoying life’s pleasures.",
  "6": "With the ruler of the 2nd house in the 6th house, your values and possessions are closely tied to work and health. You may find that you express yourself through your job or daily routines. This placement can also indicate a strong desire for order and a talent for taking care of yourself and others.",
  "7": "With the ruler of the 2nd house in the 7th house, your values and possessions are closely tied to relationships and partnerships. You may find that you express yourself through your interactions with others. This placement can also indicate a strong desire for companionship and a talent for forming close connections.",
  "8": "With the ruler of the 2nd house in the 8th house, your values and possessions are closely tied to transformation and shared resources. You may find that you express yourself through deep emotional connections and experiences. This placement can also indicate a strong desire for intimacy and a talent for navigating complex emotional landscapes.",
  "9": "With the ruler of the 2nd house in the 9th house, your values and possessions are closely tied to philosophy and higher learning. You may find that you express yourself through your beliefs and worldview. This placement can also indicate a strong desire for adventure and a talent for exploring new ideas and cultures.",
  "10": "With the ruler of the 2nd house in the 10th house, your values and possessions are closely tied to career and public image. You may find that you express yourself through your professional achievements and reputation. This placement can also indicate a strong desire for success and a talent for leadership.",
  "11": "With the ruler of the 2nd house in the 11th house, your values and possessions are closely tied to friendships and social groups. You may find that you express yourself through your connections with others. This placement can also indicate a strong desire for community and a talent for networking.",
  "12": "With the ruler of the 2nd house in the 12th house, your values and possessions are closely tied to the subconscious and spiritual realms. You may find that you express yourself through introspection and connection to something greater than yourself. This placement can also indicate a strong desire for solitude and a talent for understanding the deeper mysteries of life.",
};

export const thirdHouseRulershipInterpretations = {
  "1": "With the ruler of the 3rd house in the 1st house, your communication and learning style is closely tied to your sense of self and physical body. You may find that you express yourself through writing, speaking, or other forms of communication. This placement can also indicate a strong desire for intellectual stimulation and a talent for learning new things.",
  "2": "With the ruler of the 3rd house in the 2nd house, your communication and learning style is closely tied to your values and possessions. You may find that you express yourself through writing, speaking, or other forms of communication. This placement can also indicate a strong desire for intellectual stimulation and a talent for learning new things.",
  "3": "With the ruler of the 3rd house in the 3rd house, your communication and learning style is closely tied to your sense of self and physical body. You may find that you express yourself through writing, speaking, or other forms of communication. This placement can also indicate a strong desire for intellectual stimulation and a talent for learning new things.",
  "4": "With the ruler of the 3rd house in the 4th house, your communication and learning style is closely tied to your home and family. You may find that you express yourself through writing, speaking, or other forms of communication. This placement can also indicate a strong desire for intellectual stimulation and a talent for learning new things.",
  "5": "With the ruler of the 3rd house in the 5th house, your communication and learning style is closely tied to creativity and self-expression. You may find that you express yourself through writing, speaking, or other forms of communication. This placement can also indicate a strong desire for intellectual stimulation and a talent for learning new things.",
  "6": "With the ruler of the 3rd house in the 6th house, your communication and learning style is closely tied to work and health. You may find that you express yourself through writing, speaking, or other forms of communication. This placement can also indicate a strong desire for intellectual stimulation and a talent for learning new things.",
  "7": "With the ruler of the 3rd house in the 7th house, your communication and learning style is closely tied to relationships and partnerships. You may find that you express yourself through writing, speaking, or other forms of communication. This placement can also indicate a strong desire for intellectual stimulation and a talent for learning new things.",
  "8": "With the ruler of the 3rd house in the 8th house, your communication and learning style is closely tied to transformation and shared resources. You may find that you express yourself through writing, speaking, or other forms of communication. This placement can also indicate a strong desire for intellectual stimulation and a talent for learning new things.",
  "9": "With the ruler of the 3rd house in the 9th house, your communication and learning style is closely tied to philosophy and higher learning. You may find that you express yourself through writing, speaking, or other forms of communication. This placement can also indicate a strong desire for intellectual stimulation and a talent for learning new things.",
  "10": "With the ruler of the 3rd house in the 10th house, your communication and learning style is closely tied to career and public image. You may find that you express yourself through writing, speaking, or other forms of communication. This placement can also indicate a strong desire for intellectual stimulation and a talent for learning new things.",
  "11": "With the ruler of the 3rd house in the 11th house, your communication and learning style is closely tied to friendships and social groups. You may find that you express yourself through writing, speaking, or other forms of communication. This placement can also indicate a strong desire for intellectual stimulation and a talent for learning new things.",
  "12": "With the ruler of the 3rd house in the 12th house, your communication and learning style is closely tied to the subconscious and spiritual realms. You may find that you express yourself through writing, speaking, or other forms of communication. This placement can also indicate a strong desire for intellectual stimulation and a talent for learning new things.",
};

export const fourthHouseRulershipInterpretations = {
  "1": "With the ruler of the 4th house in the 1st house, your home and family life is closely tied to your sense of self and physical body. You may find that your identity is influenced by your upbringing and family dynamics. This placement can also indicate a strong desire for emotional security and a talent for creating a comfortable home environment.",
  "2": "With the ruler of the 4th house in the 2nd house, your home and family life is closely tied to your values and possessions. You may find that your identity is influenced by your upbringing and family dynamics. This placement can also indicate a strong desire for emotional security and a talent for creating a comfortable home environment.",
  "3": "With the ruler of the 4th house in the 3rd house, your home and family life is closely tied to communication and learning. You may find that your identity is influenced by your upbringing and family dynamics. This placement can also indicate a strong desire for emotional security and a talent for creating a comfortable home environment.",
  "4": "With the ruler of the 4th house in the 4th house, your home and family life is closely tied to your sense of self and physical body. You may find that your identity is influenced by your upbringing and family dynamics. This placement can also indicate a strong desire for emotional security and a talent for creating a comfortable home environment.",
  "5": "With the ruler of the 4th house in the 5th house, your home and family life is closely tied to creativity and self-expression. You may find that your identity is influenced by your upbringing and family dynamics. This placement can also indicate a strong desire for emotional security and a talent for creating a comfortable home environment.",
  "6": "With the ruler of the 4th house in the 6th house, your home and family life is closely tied to work and health. You may find that your identity is influenced by your upbringing and family dynamics. This placement can also indicate a strong desire for emotional security and a talent for creating a comfortable home environment.",
  "7": "With the ruler of the 4th house in the 7th house, your home and family life is closely tied to relationships and partnerships. You may find that your identity is influenced by your upbringing and family dynamics. This placement can also indicate a strong desire for emotional security and a talent for creating a comfortable home environment.",
  "8": "With the ruler of the 4th house in the 8th house, your home and family life is closely tied to transformation and shared resources. You may find that your identity is influenced by your upbringing and family dynamics. This placement can also indicate a strong desire for emotional security and a talent for creating a comfortable home environment.",
  "9": "With the ruler of the 4th house in the 9th house, your home and family life is closely tied to philosophy and higher learning. You may find that your identity is influenced by your upbringing and family dynamics. This placement can also indicate a strong desire for emotional security and a talent for creating a comfortable home environment.",
  "10": "With the ruler of the 4th house in the 10th house, your home and family life is closely tied to career and public image. You may find that your identity is influenced by your upbringing and family dynamics. This placement can also indicate a strong desire for emotional security and a talent for creating a comfortable home environment.",
  "11": "With the ruler of the 4th house in the 11th house, your home and family life is closely tied to friendships and social groups. You may find that your identity is influenced by your upbringing and family dynamics. This placement can also indicate a strong desire for emotional security and a talent for creating a comfortable home environment.",
  "12": "With the ruler of the 4th house in the 12th house, your home and family life is closely tied to the subconscious and spiritual realms. You may find that your identity is influenced by your upbringing and family dynamics. This placement can also indicate a strong desire for emotional security and a talent for creating a comfortable home environment.",
};

export const fifthHouseRulershipInterpretations = {
  "1": "With the ruler of the 5th house in the 1st house, your creativity and self-expression is closely tied to your sense of self and physical body. You may find that you express yourself through art, music, or other creative pursuits. This placement can also indicate a strong desire for romance and a talent for enjoying life’s pleasures.",
  "2": "With the ruler of the 5th house in the 2nd house, your creativity and self-expression is closely tied to your values and possessions. You may find that you express yourself through art, music, or other creative pursuits. This placement can also indicate a strong desire for romance and a talent for enjoying life’s pleasures.",
  "3": "With the ruler of the 5th house in the 3rd house, your creativity and self-expression is closely tied to communication and learning. You may find that you express yourself through art, music, or other creative pursuits. This placement can also indicate a strong desire for romance and a talent for enjoying life’s pleasures.",
  "4": "With the ruler of the 5th house in the 4th house, your creativity and self-expression is closely tied to your home and family. You may find that you express yourself through art, music, or other creative pursuits. This placement can also indicate a strong desire for romance and a talent for enjoying life’s pleasures.",
  "5": "With the ruler of the 5th house in the 5th house, your creativity and self-expression is closely tied to your sense of self and physical body. You may find that you express yourself through art, music, or other creative pursuits. This placement can also indicate a strong desire for romance and a talent for enjoying life’s pleasures.",
  "6": "With the ruler of the 5th house in the 6th house, your creativity and self-expression is closely tied to work and health. You may find that you express yourself through art, music, or other creative pursuits. This placement can also indicate a strong desire for romance and a talent for enjoying life’s pleasures.",
  "7": "With the ruler of the 5th house in the 7th house, your creativity and self-expression is closely tied to relationships and partnerships. You may find that you express yourself through art, music, or other creative pursuits. This placement can also indicate a strong desire for romance and a talent for enjoying life’s pleasures.",
  "8": "With the ruler of the 5th house in the 8th house, your creativity and self-expression is closely tied to transformation and shared resources. You may find that you express yourself through art, music, or other creative pursuits. This placement can also indicate a strong desire for romance and a talent for enjoying life’s pleasures.",
  "9": "With the ruler of the 5th house in the 9th house, your creativity and self-expression is closely tied to philosophy and higher learning. You may find that you express yourself through art, music, or other creative pursuits. This placement can also indicate a strong desire for romance and a talent for enjoying life’s pleasures.",
  "10": "With the ruler of the 5th house in the 10th house, your creativity and self-expression is closely tied to career and public image. You may find that you express yourself through art, music, or other creative pursuits. This placement can also indicate a strong desire for romance and a talent for enjoying life’s pleasures.",
  "11": "With the ruler of the 5th house in the 11th house, your creativity and self-expression is closely tied to friendships and social groups. You may find that you express yourself through art, music, or other creative pursuits. This placement can also indicate a strong desire for romance and a talent for enjoying life’s pleasures.",
  "12": "With the ruler of the 5th house in the 12th house, your creativity and self-expression is closely tied to the subconscious and spiritual realms. You may find that you express yourself through art, music, or other creative pursuits. This placement can also indicate a strong desire for romance and a talent for enjoying life’s pleasures.",
};

export const sixthHouseRulershipInterpretations = {
  "1": "With the ruler of the 6th house in the 1st house, your work and health is closely tied to your sense of self and physical body. You may find that you express yourself through your job or daily routines. This placement can also indicate a strong desire for order and a talent for taking care of yourself and others.",
  "2": "With the ruler of the 6th house in the 2nd house, your work and health is closely tied to your values and possessions. You may find that you express yourself through your job or daily routines. This placement can also indicate a strong desire for order and a talent for taking care of yourself and others.",
  "3": "With the ruler of the 6th house in the 3rd house, your work and health is closely tied to communication and learning. You may find that you express yourself through your job or daily routines. This placement can also indicate a strong desire for order and a talent for taking care of yourself and others.",
  "4": "With the ruler of the 6th house in the 4th house, your work and health is closely tied to your home and family. You may find that you express yourself through your job or daily routines. This placement can also indicate a strong desire for order and a talent for taking care of yourself and others.",
  "5": "With the ruler of the 6th house in the 5th house, your work and health is closely tied to creativity and self-expression. You may find that you express yourself through your job or daily routines. This placement can also indicate a strong desire for order and a talent for taking care of yourself and others.",
  "6": "With the ruler of the 6th house in the 6th house, your work and health is closely tied to your sense of self and physical body. You may find that you express yourself through your job or daily routines. This placement can also indicate a strong desire for order and a talent for taking care of yourself and others.",
  "7": "With the ruler of the 6th house in the 7th house, your work and health is closely tied to relationships and partnerships. You may find that you express yourself through your job or daily routines. This placement can also indicate a strong desire for order and a talent for taking care of yourself and others.",
  "8": "With the ruler of the 6th house in the 8th house, your work and health is closely tied to transformation and shared resources. You may find that you express yourself through your job or daily routines. This placement can also indicate a strong desire for order and a talent for taking care of yourself and others.",
  "9": "With the ruler of the 6th house in the 9th house, your work and health is closely tied to philosophy and higher learning. You may find that you express yourself through your job or daily routines. This placement can also indicate a strong desire for order and a talent for taking care of yourself and others.",
  "10": "With the ruler of the 6th house in the 10th house, your work and health is closely tied to career and public image. You may find that you express yourself through your job or daily routines. This placement can also indicate a strong desire for order and a talent for taking care of yourself and others.",
  "11": "With the ruler of the 6th house in the 11th house, your work and health is closely tied to friendships and social groups. You may find that you express yourself through your job or daily routines. This placement can also indicate a strong desire for order and a talent for taking care of yourself and others.",
  "12": "With the ruler of the 6th house in the 12th house, your work and health is closely tied to the subconscious and spiritual realms. You may find that you express yourself through your job or daily routines. This placement can also indicate a strong desire for order and a talent for taking care of yourself and others.",
};

export const seventhHouseRulershipInterpretations = {
  "1": "With the ruler of the 7th house in the 1st house, your relationships and partnerships are closely tied to your sense of self and physical body. You may find that you express yourself through your interactions with others. This placement can also indicate a strong desire for companionship and a talent for forming close connections.",
  "2": "With the ruler of the 7th house in the 2nd house, your relationships and partnerships are closely tied to your values and possessions. You may find that you express yourself through your interactions with others. This placement can also indicate a strong desire for companionship and a talent for forming close connections.",
  "3": "With the ruler of the 7th house in the 3rd house, your relationships and partnerships are closely tied to communication and learning. You may find that you express yourself through your interactions with others. This placement can also indicate a strong desire for companionship and a talent for forming close connections.",
  "4": "With the ruler of the 7th house in the 4th house, your relationships and partnerships are closely tied to your home and family. You may find that you express yourself through your interactions with others. This placement can also indicate a strong desire for companionship and a talent for forming close connections.",
  "5": "With the ruler of the 7th house in the 5th house, your relationships and partnerships are closely tied to creativity and self-expression. You may find that you express yourself through your interactions with others. This placement can also indicate a strong desire for companionship and a talent for forming close connections.",
  "6": "With the ruler of the 7th house in the 6th house, your relationships and partnerships are closely tied to work and health. You may find that you express yourself through your interactions with others. This placement can also indicate a strong desire for companionship and a talent for forming close connections.",
  "7": "With the ruler of the 7th house in the 7th house, your relationships and partnerships are closely tied to your sense of self and physical body. You may find that you express yourself through your interactions with others. This placement can also indicate a strong desire for companionship and a talent for forming close connections.",
  "8": "With the ruler of the 7th house in the 8th house, your relationships and partnerships are closely tied to transformation and shared resources. You may find that you express yourself through your interactions with others. This placement can also indicate a strong desire for companionship and a talent for forming close connections.",
  "9": "With the ruler of the 7th house in the 9th house, your relationships and partnerships are closely tied to philosophy and higher learning. You may find that you express yourself through your interactions with others. This placement can also indicate a strong desire for companionship and a talent for forming close connections.",
  "10": "With the ruler of the 7th house in the 10th house, your relationships and partnerships are closely tied to career and public image. You may find that you express yourself through your interactions with others. This placement can also indicate a strong desire for companionship and a talent for forming close connections.",
  "11": "With the ruler of the 7th house in the 11th house, your relationships and partnerships are closely tied to friendships and social groups. You may find that you express yourself through your interactions with others. This placement can also indicate a strong desire for companionship and a talent for forming close connections.",
  "12": "With the ruler of the 7th house in the 12th house, your relationships and partnerships are closely tied to the subconscious and spiritual realms. You may find that you express yourself through your interactions with others. This placement can also indicate a strong desire for companionship and a talent for forming close connections.",
};

export const eighthHouseRulershipInterpretations = {
  "1": "With the ruler of the 8th house in the 1st house, your transformation and shared resources are closely tied to your sense of self and physical body. You may find that you express yourself through deep emotional connections and experiences. This placement can also indicate a strong desire for intimacy and a talent for navigating complex emotional landscapes.",
  "2": "With the ruler of the 8th house in the 2nd house, your transformation and shared resources are closely tied to your values and possessions. You may find that you express yourself through deep emotional connections and experiences. This placement can also indicate a strong desire for intimacy and a talent for navigating complex emotional landscapes.",
  "3": "With the ruler of the 8th house in the 3rd house, your transformation and shared resources are closely tied to communication and learning. You may find that you express yourself through deep emotional connections and experiences. This placement can also indicate a strong desire for intimacy and a talent for navigating complex emotional landscapes.",
  "4": "With the ruler of the 8th house in the 4th house, your transformation and shared resources are closely tied to your home and family. You may find that you express yourself through deep emotional connections and experiences. This placement can also indicate a strong desire for intimacy and a talent for navigating complex emotional landscapes.",
  "5": "With the ruler of the 8th house in the 5th house, your transformation and shared resources are closely tied to creativity and self-expression. You may find that you express yourself through deep emotional connections and experiences. This placement can also indicate a strong desire for intimacy and a talent for navigating complex emotional landscapes.",
  "6": "With the ruler of the 8th house in the 6th house, your transformation and shared resources are closely tied to work and health. You may find that you express yourself through deep emotional connections and experiences. This placement can also indicate a strong desire for intimacy and a talent for navigating complex emotional landscapes.",
  "7": "With the ruler of the 8th house in the 7th house, your transformation and shared resources are closely tied to relationships and partnerships. You may find that you express yourself through deep emotional connections and experiences. This placement can also indicate a strong desire for intimacy and a talent for navigating complex emotional landscapes.",
  "8": "With the ruler of the 8th house in the 8th house, your transformation and shared resources are closely tied to your sense of self and physical body. You may find that you express yourself through deep emotional connections and experiences. This placement can also indicate a strong desire for intimacy and a talent for navigating complex emotional landscapes.",
  "9": "With the ruler of the 8th house in the 9th house, your transformation and shared resources are closely tied to philosophy and higher learning. You may find that you express yourself through deep emotional connections and experiences. This placement can also indicate a strong desire for intimacy and a talent for navigating complex emotional landscapes.",
  "10": "With the ruler of the 8th house in the 10th house, your transformation and shared resources are closely tied to career and public image. You may find that you express yourself through deep emotional connections and experiences. This placement can also indicate a strong desire for intimacy and a talent for navigating complex emotional landscapes.",
  "11": "With the ruler of the 8th house in the 11th house, your transformation and shared resources are closely tied to friendships and social groups. You may find that you express yourself through deep emotional connections and experiences. This placement can also indicate a strong desire for intimacy and a talent for navigating complex emotional landscapes.",
  "12": "With the ruler of the 8th house in the 12th house, your transformation and shared resources are closely tied to the subconscious and spiritual realms. You may find that you express yourself through deep emotional connections and experiences. This placement can also indicate a strong desire for intimacy and a talent for navigating complex emotional landscapes.",
};

export const ninthHouseRulershipInterpretations = {
  "1": "With the ruler of the 9th house in the 1st house, your philosophy and higher learning is closely tied to your sense of self and physical body. You may find that you express yourself through your beliefs and worldview. This placement can also indicate a strong desire for adventure and a talent for exploring new ideas and cultures.",
  "2": "With the ruler of the 9th house in the 2nd house, your philosophy and higher learning is closely tied to your values and possessions. You may find that you express yourself through your beliefs and worldview. This placement can also indicate a strong desire for adventure and a talent for exploring new ideas and cultures.",
  "3": "With the ruler of the 9th house in the 3rd house, your philosophy and higher learning is closely tied to communication and learning. You may find that you express yourself through your beliefs and worldview. This placement can also indicate a strong desire for adventure and a talent for exploring new ideas and cultures.",
  "4": "With the ruler of the 9th house in the 4th house, your philosophy and higher learning is closely tied to your home and family. You may find that you express yourself through your beliefs and worldview. This placement can also indicate a strong desire for adventure and a talent for exploring new ideas and cultures.",
  "5": "With the ruler of the 9th house in the 5th house, your philosophy and higher learning is closely tied to creativity and self-expression. You may find that you express yourself through your beliefs and worldview. This placement can also indicate a strong desire for adventure and a talent for exploring new ideas and cultures.",
  "6": "With the ruler of the 9th house in the 6th house, your philosophy and higher learning is closely tied to work and health. You may find that you express yourself through your beliefs and worldview. This placement can also indicate a strong desire for adventure and a talent for exploring new ideas and cultures.",
  "7": "With the ruler of the 9th house in the 7th house, your philosophy and higher learning is closely tied to relationships and partnerships. You may find that you express yourself through your beliefs and worldview. This placement can also indicate a strong desire for adventure and a talent for exploring new ideas and cultures.",
  "8": "With the ruler of the 9th house in the 8th house, your philosophy and higher learning is closely tied to transformation and shared resources. You may find that you express yourself through your beliefs and worldview. This placement can also indicate a strong desire for adventure and a talent for exploring new ideas and cultures.",
  "9": "With the ruler of the 9th house in the 9th house, your philosophy and higher learning is closely tied to your sense of self and physical body. You may find that you express yourself through your beliefs and worldview. This placement can also indicate a strong desire for adventure and a talent for exploring new ideas and cultures.",
  "10": "With the ruler of the 9th house in the 10th house, your philosophy and higher learning is closely tied to career and public image. You may find that you express yourself through your beliefs and worldview. This placement can also indicate a strong desire for adventure and a talent for exploring new ideas and cultures.",
  "11": "With the ruler of the 9th house in the 11th house, your philosophy and higher learning is closely tied to friendships and social groups. You may find that you express yourself through your beliefs and worldview. This placement can also indicate a strong desire for adventure and a talent for exploring new ideas and cultures.",
  "12": "With the ruler of the 9th house in the 12th house, your philosophy and higher learning is closely tied to the subconscious and spiritual realms. You may find that you express yourself through your beliefs and worldview. This placement can also indicate a strong desire for adventure and a talent for exploring new ideas and cultures.",
};

export const tenthHouseRulershipInterpretations = {
  "1": "With the ruler of the 10th house in the 1st house, your career and public image is closely tied to your sense of self and physical body. You may find that you express yourself through your professional achievements and reputation. This placement can also indicate a strong desire for success and a talent for leadership.",
  "2": "With the ruler of the 10th house in the 2nd house, your career and public image is closely tied to your values and possessions. You may find that you express yourself through your professional achievements and reputation. This placement can also indicate a strong desire for success and a talent for leadership.",
  "3": "With the ruler of the 10th house in the 3rd house, your career and public image is closely tied to communication and learning. You may find that you express yourself through your professional achievements and reputation. This placement can also indicate a strong desire for success and a talent for leadership.",
  "4": "With the ruler of the 10th house in the 4th house, your career and public image is closely tied to your home and family. You may find that you express yourself through your professional achievements and reputation. This placement can also indicate a strong desire for success and a talent for leadership.",
  "5": "With the ruler of the 10th house in the 5th house, your career and public image is closely tied to creativity and self-expression. You may find that you express yourself through your professional achievements and reputation. This placement can also indicate a strong desire for success and a talent for leadership.",
  "6": "With the ruler of the 10th house in the 6th house, your career and public image is closely tied to work and health. You may find that you express yourself through your professional achievements and reputation. This placement can also indicate a strong desire for success and a talent for leadership.",
  "7": "With the ruler of the 10th house in the 7th house, your career and public image is closely tied to relationships and partnerships. You may find that you express yourself through your professional achievements and reputation. This placement can also indicate a strong desire for success and a talent for leadership.",
  "8": "With the ruler of the 10th house in the 8th house, your career and public image is closely tied to transformation and shared resources. You may find that you express yourself through your professional achievements and reputation. This placement can also indicate a strong desire for success and a talent for leadership.",
  "9": "With the ruler of the 10th house in the 9th house, your career and public image is closely tied to philosophy and higher learning. You may find that you express yourself through your professional achievements and reputation. This placement can also indicate a strong desire for success and a talent for leadership.",
  "10": "With the ruler of the 10th house in the 10th house, your career and public image is closely tied to your sense of self and physical body. You may find that you express yourself through your professional achievements and reputation. This placement can also indicate a strong desire for success and a talent for leadership.",
  "11": "With the ruler of the 10th house in the 11th house, your career and public image is closely tied to friendships and social groups. You may find that you express yourself through your professional achievements and reputation. This placement can also indicate a strong desire for success and a talent for leadership.",
  "12": "With the ruler of the 10th house in the 12th house, your career and public image is closely tied to the subconscious and spiritual realms. You may find that you express yourself through your professional achievements and reputation. This placement can also indicate a strong desire for success and a talent for leadership.",
};

export const eleventhHouseRulershipInterpretations = {
  "1": "With the ruler of the 11th house in the 1st house, your friendships and social groups are closely tied to your sense of self and physical body. You may find that you express yourself through your interactions with friends and social circles. This placement can also indicate a strong desire for community and a talent for forming meaningful connections.",
  "2": "With the ruler of the 11th house in the 2nd house, your friendships and social groups are closely tied to your values and possessions. You may find that you express yourself through your interactions with friends and social circles. This placement can also indicate a strong desire for community and a talent for forming meaningful connections.",
  "3": "With the ruler of the 11th house in the 3rd house, your friendships and social groups are closely tied to communication and learning. You may find that you express yourself through your interactions with friends and social circles. This placement can also indicate a strong desire for community and a talent for forming meaningful connections.",
  "4": "With the ruler of the 11th house in the 4th house, your friendships and social groups are closely tied to your home and family. You may find that you express yourself through your interactions with friends and social circles. This placement can also indicate a strong desire for community and a talent for forming meaningful connections.",
  "5": "With the ruler of the 11th house in the 5th house, your friendships and social groups are closely tied to creativity and self-expression. You may find that you express yourself through your interactions with friends and social circles. This placement can also indicate a strong desire for community and a talent for forming meaningful connections.",
  "6": "With the ruler of the 11th house in the 6th house, your friendships and social groups are closely tied to work and health. You may find that you express yourself through your interactions with friends and social circles. This placement can also indicate a strong desire for community and a talent for forming meaningful connections.",
  "7": "With the ruler of the 11th house in the 7th house, your friendships and social groups are closely tied to relationships and partnerships. You may find that you express yourself through your interactions with friends and social circles. This placement can also indicate a strong desire for community and a talent for forming meaningful connections.",
  "8": "With the ruler of the 11th house in the 8th house, your friendships and social groups are closely tied to transformation and shared resources. You may find that you express yourself through your interactions with friends and social circles. This placement can also indicate a strong desire for community and a talent for forming meaningful connections.",
  "9": "With the ruler of the 11th house in the 9th house, your friendships and social groups are closely tied to philosophy and higher learning. You may find that you express yourself through your interactions with friends and social circles. This placement can also indicate a strong desire for community and a talent for forming meaningful connections.",
  "10": "With the ruler of the 11th house in the 10th house, your friendships and social groups are closely tied to career and public image. You may find that you express yourself through your interactions with friends and social circles. This placement can also indicate a strong desire for community and a talent for forming meaningful connections.",
  "11": "With the ruler of the 11th house in the 11th house, your friendships and social groups are closely tied to your sense of self and physical body. You may find that you express yourself through your interactions with friends and social circles. This placement can also indicate a strong desire for community and a talent for forming meaningful connections.",
  "12": "With the ruler of the 11th house in the 12th house, your friendships and social groups are closely tied to the subconscious and spiritual realms. You may find that you express yourself through your interactions with friends and social circles. This placement can also indicate a strong desire for community and a talent for forming meaningful connections.",
};

export const twelfthHouseRulershipInterpretations = {
  "1": "With the ruler of the 12th house in the 1st house, your subconscious and spiritual realms are closely tied to your sense of self and physical body. You may find that you express yourself through introspection and spiritual practices. This placement can also indicate a strong desire for solitude and a talent for connecting with the unseen.",
  "2": "With the ruler of the 12th house in the 2nd house, your subconscious and spiritual realms are closely tied to your values and possessions. You may find that you express yourself through introspection and spiritual practices. This placement can also indicate a strong desire for solitude and a talent for connecting with the unseen.",
  "3": "With the ruler of the 12th house in the 3rd house, your subconscious and spiritual realms are closely tied to communication and learning. You may find that you express yourself through introspection and spiritual practices. This placement can also indicate a strong desire for solitude and a talent for connecting with the unseen.",
  "4": "With the ruler of the 12th house in the 4th house, your subconscious and spiritual realms are closely tied to your home and family. You may find that you express yourself through introspection and spiritual practices. This placement can also indicate a strong desire for solitude and a talent for connecting with the unseen.",
  "5": "With the ruler of the 12th house in the 5th house, your subconscious and spiritual realms are closely tied to creativity and self-expression. You may find that you express yourself through introspection and spiritual practices. This placement can also indicate a strong desire for solitude and a talent for connecting with the unseen.",
  "6": "With the ruler of the 12th house in the 6th house, your subconscious and spiritual realms are closely tied to work and health. You may find that you express yourself through introspection and spiritual practices. This placement can also indicate a strong desire for solitude and a talent for connecting with the unseen.",
  "7": "With the ruler of the 12th house in the 7th house, your subconscious and spiritual realms are closely tied to relationships and partnerships. You may find that you express yourself through introspection and spiritual practices. This placement can also indicate a strong desire for solitude and a talent for connecting with the unseen.",
  "8": "With the ruler of the 12th house in the 8th house, your subconscious and spiritual realms are closely tied to transformation and shared resources. You may find that you express yourself through introspection and spiritual practices. This placement can also indicate a strong desire for solitude and a talent for connecting with the unseen.",
  "9": "With the ruler of the 12th house in the 9th house, your subconscious and spiritual realms are closely tied to philosophy and higher learning. You may find that you express yourself through introspection and spiritual practices. This placement can also indicate a strong desire for solitude and a talent for connecting with the unseen.",
  "10": "With the ruler of the 12th house in the 10th house, your subconscious and spiritual realms are closely tied to career and public image. You may find that you express yourself through introspection and spiritual practices. This placement can also indicate a strong desire for solitude and a talent for connecting with the unseen.",
  "11": "With the ruler of the 12th house in the 11th house, your subconscious and spiritual realms are closely tied to friendships and social groups. You may find that you express yourself through introspection and spiritual practices. This placement can also indicate a strong desire for solitude and a talent for connecting with the unseen.",
  "12": "With the ruler of the 12th house in the 12th house, your subconscious and spiritual realms are closely tied to your sense of self and physical body. You may find that you express yourself through introspection and spiritual practices. This placement can also indicate a strong desire for solitude and a talent for connecting with the unseen.",
};
